artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1YbawRTUPhkdgdqUUJ9BJuI1Z3SSRoWs3/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  data_file: artifacts/data_ingestion/MatchAnalysis.csv


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pkl
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pkl

prepare_data:
  root_dir: artifacts/prepare_data
  prepared_data_path: artifacts/prepare_data/prepared_data.csv
  feature_columns: [
      blueGold, blueMinionsKilled, blueJungleMinionsKilled, blueAvgLevel, 
      redGold,  redMinionsKilled,  redJungleMinionsKilled,  redAvgLevel,
      blueChampKills, blueHeraldKills, blueDragonKills, blueTowersDestroyed,
      redChampKills, redHeraldKills, redDragonKills, redTowersDestroyed
  ]
  target_column: blue_win

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pkl